print('ifjsiodvnsdvn,kk')
print('riaeofjlerijgvr')
print('darw a little heart for you')
print('     ****          ****')
print('   ********      ********')
print('  ************************')
print(' **************************')
print('  ************************')
print('    ********************')
print('      ****************')
print('        ***********')
print('           *****'   )
print('中文测试')